### ISSUE TITLE
Inquiry About API Longevity

### ISSUE THREAD

**Issue by hitarth-gg** [Vivek-Kolhe/Nyaa-API#4]
Thank you for providing such a useful API service! I’m currently using this API in a project, and I have a quick question regarding its future availability.

Could you please let me know how long you plan to keep the API running? Additionally, I’d like to inquire about the rate limits for the API. Currently, I am making 5 calls with very little timeout in between to search for all available torrents of a single anime.

Thank you.

**Comment by Vivek-Kolhe** [comment]
The API is currently hosted on Render using a free account. It will remain available as long as Render offers free accounts or until I find some other alternative. I would like to keep it running as long as possible since I also use it. 
As of now, there is no rate limiter in place, which is fine as long as you include a timeout between your requests. Just make sure you don't spam requests, if there is a spam, the site (nyaa.si) may ban the IP address, and Render does not provide a large pool of IP addresses like Heroku used to.
